export const im = [{a:"https://www.nifafinearts.com/images/homegallery/img1.jpg",id:"1",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img2.jpg" ,id:"2",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img3.jpg" ,id:"3",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img4.jpg",id:"4",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img7.jpg",id:"7",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img16.jpeg",id:"17",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img9.jpg",id:"9",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img5.JPG",id:"5",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img6.JPG",id:"5",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img8.jpg",id:"8",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img10.jpg",id:"10",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img11.jpg",id:"11",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img12.jpg",id:"12",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img13.jpg",id:"13",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img14.jpeg",id:"14",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img15.jpeg",id:"15",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img16.jpeg",id:"16",height:"270px"},

{a:"https://www.nifafinearts.com/images/homegallery/img17.jpg",id:"17",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img18.jpeg",id:"18",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img19.jpg",id:"19",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img20.jpeg",id:"20",height:"270px"},
{a:"https://www.nifafinearts.com/images/homegallery/img21.jpeg",id:"21",height:"270px"},

]